version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Port for React development server
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  # Port for FastAPI application
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:password@database:5432/myappdb"
      SECRET_KEY: "my-super-secret-key"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_HOURS: 24
  database:
    image: postgres:15
    ports:
      - "5432:5432"  # PostgreSQL port
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myappdb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db/init-scripts:/docker-entrypoint-initdb.d